language: python
python:
  - "3.6"
service:
  - mysql
env:
  -DJANGO=2.0.2 DB=mysql
install:
  - pip install -r requirements.txt
before_script:
  - mysql -e 'create database test;' -u root
script:
  - cd valevasion
  - mv valevasion/.env.example valevasion/.env
  - python manage.py test
