version: '3'

services:
  valevasion-db:
    image: mariadb
    restart: always
    command: ['--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    environment:
        MYSQL_DATABASE: valevasion
        MYSQL_USER: root
        MYSQL_PASSWORD: valevasion
        MYSQL_ROOT_PASSWORD: valevasion
  valevasion-web:
    build: .
    command: bash -c "python valevasion/manage.py flush --noinput && python valevasion/manage.py collectstatic --noinput && python valevasion/manage.py makemigrations && python valevasion/manage.py migrate && python valevasion/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - valevasion-db