# Generated by Django 2.0.8 on 2018-11-10 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import tinymce.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', tinymce.models.HTMLField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('image', models.ImageField(upload_to='')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('update', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(related_name='articles', to='travels.Tag')),
                ('gallery_article',
                 models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   related_name='gallery_article', to='travels.Gallery')),
            ],
            options={
                'ordering': ('-pub_date',)
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=255, verbose_name='Message')),
                ('isAccepted', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                              to='travels.Article')),
                ('author',
                 models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('gallery',
                 models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gallery',
                                   to='travels.Gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('isShow', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
