# Generated by Django 2.0.2 on 2018-02-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('body',)},
        ),
    ]
