# Generated by Django 2.0.2 on 2018-02-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_remove_tag_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('body',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='article',
            name='date_in',
        ),
        migrations.RemoveField(
            model_name='article',
            name='date_out',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
        migrations.AddField(
            model_name='tag',
            name='articles',
            field=models.ManyToManyField(to='travels.Article'),
        ),
    ]
