# Generated by Django 2.0.2 on 2018-02-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_auto_20180215_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles', to='travels.Tag'),
        ),
    ]
