# Generated by Django 2.0.2 on 2018-02-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_auto_20180215_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='travels.Tag'),
        ),
    ]
