# Generated by Django 2.0.2 on 2018-02-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_auto_20180215_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='price',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
