# Generated by Django 2.0.2 on 2018-02-16 19:44

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_auto_20180216_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
