# Generated by Django 2.0.2 on 2018-02-22 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0006_comment_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
    ]
