# Generated by Django 2.0.2 on 2018-02-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0010_auto_20180223_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('pub_date',)},
        ),
    ]
