# Generated by Django 2.0.4 on 2018-04-06 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0013_auto_20180303_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('gallery', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='travels.Gallery')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='gallery_article',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_article', to='travels.Gallery'),
        ),
    ]
