# Generated by Django 2.0.2 on 2018-04-08 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20180305_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire'),
        ),
    ]
