# Generated by Django 2.0.2 on 2018-04-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_auto_20180408_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='content',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Sujet'),
        ),
    ]
